### ISSUE TITLE
Register !hugs to same function as !hug

### ISSUE THREAD

**Issue by adrien-s** [Art-SoftWare/discordBot#10]
Register !hugs, !snugs, !snuggles as the same command as !hug.
  - [x] make a RegisterCommand*s*() to allow multiple command declaration at once
  - [x] declare hugs/hugs/snugs/snuggles

**Comment by maxlefou** [comment]
Maybe making a way so multiple commands can lead to a same function. 

Like, !hugs, !snugs and !snuggles redirecting to !hug, for example

**Comment by adrien-s** [comment]
Not a bad idea, just make a list. (I'll start with that)

**Comment by adrien-s** [comment]
Done in d26c2b5 . Please suggest for more command aliases if you think of any useful idea ! /)
